### ISSUE TITLE
Documentation and Comments

### ISSUE THREAD

**Issue by markaduol** [atom/teletype-crdt#10]
Perhaps consider adding a comment or two to the codebase? Perhaps even documenting some of the functions so that we can understand how exactly your CRDT implementation works and hence, can contribute some code for performance improvements?

**Comment by jasonrudolph** [comment]
:wave: Hi @markaduol: Thanks for your interest. 💟

This is definitely something we'd like to do. Since we [already have this captured in the TODO list in our README](https://github.com/atom/teletype-crdt/tree/bfada4da167139bd5df020b1b1c67fd687fd39cc#todo), I'm going to close this issue.
