### ISSUE TITLE
Incorrect absolute position returned from integrateOperations with multiple edits

### ISSUE THREAD

**Issue by nahk-ivanov** [atom/teletype-crdt#15]
I believe there is a bug in ```document.js``` on [line 1363](https://github.com/atom/teletype-crdt/blob/master/lib/document.js#L1363):
```
const segmentOldStart =
  lastChange
    ? traverse(>>>lastChange.oldEnd<<<, traversal(segmentNewStart, lastChange.newEnd))
    : segmentNewStart
```

If I understand the intent of the authors correctly, then it should ```traverse``` from ```lastChange.newEnd```, not ```oldEnd```.

Here's basic example. Lets assume there are two operations to integrate in the following order (1, then 2):
```
int foo() {
   /* (2) insert
       multiple lines */
   // (1) delete single line
}
```
You will have them reordered in ```collectSegments``` because of segment index (which I believe is based on the appearance order, rather than modification time/sequence number). Now having operations [2, 1] being processed by ```computeChangesForSegments```, you need to adjust absolute positions of operation 1, to make sure it accounts for all the integrated changes that appear in the document before it. These calls to ```traverse```/```traversal``` are supposed to do it, but ```traverse``` call is adding the distance to previous segment's (modification 2) ```oldEnd``` position, which for multi-line changes will be different from ```newEnd```: old (end=start) is line 1 (insertion on line 1), but new is line 2 (start=1, end=2). This causes subsequent delete operation to be adjusted off by 1 line. This, in turn, when applied to the actual editor will delete text on the previous line (```multiple lines */```) rather than the expected one (```// (1) delete single line```).

So if that is true, and it should be changed to ```newEnd```, then it might as well be replaced with just the ```segmentNewStart```, because it will always produce the same value: you measure distance from ```lastChange.newEnd``` to ```segmentNewStart``` and apply it to ```lastChange.newEnd```.

In fact, if my understanding of what is ```old``` and ```new``` (before and after current modification?) is correct, then I can't think of a case where ```oldStart``` will be different from a ```newStart``` (both insertion or deletion).

**Comment by as-cii** [comment]
The old coordinate space represents positions as if the given operations were never applied. Vice versa, the new coordinate space represents positions as if the supplied operations were there all along. The two kinds of coordinates will most likely diverge when applying a sequence of operations.

With that in mind, in that code we're trying to compute the extent of text that didn't change between two ordered segments (note that such extent will be the same in both coordinate spaces).  Then, we apply that extent to the old end of the previous segment to compute the old start of the current segment. This allows the two coordinate spaces to be computed simultaneously by just indexing coordinates for the new coordinate space in our tree representation of the document (`SegmentTree`).

One more thing to emphasize is that the order of operations doesn't matter. In fact, that routine's purpose is to turn a temporal diff (i.e., a sequence of operations) into a spatial diff (i.e., a patch that can be applied to a document that _hasn't observed_ those operations yet).

I think we can be fairly confident that the method is behaving properly, both analytically and empirically (we run lots of property tests against it and we haven't found failures so far). If a problem exists, however, and you could demonstrate it with a unit test, that would be much appreciated. 

Closing this for now, thanks for the feedback! 🙇

**Comment by nahk-ivanov** [comment]
Thanks for explaining the meaning of old and new, that makes sense. Although this means that there is nothing in the edits returned by ```integrateOperations``` that can be directly applied to the plain text string. What I mean is that to integrate changes to the plain string you need to serialize them, where every following change has it's position adjusted as if previous change was already applied.

I looked at the tests and it seems like ```LocalDocument``` tries to work-around the problem by just going over returned operations backwards ([line 14](https://github.com/atom/teletype-crdt/blob/508688fdcebb7b398638740b534fb92a648aae95/test/helpers/local-document.js#L14)) while using ```old``` position. It is funny, because I thought about it as well at the very beginning and turned it down immediately, because in my mind that solution would fall short if you have edits like:
```
(1)<public class Foo {
    (2)<public void Bar() { }>
}>
```
I wrote a test for that and to my surprise - it succeeded. Debugging through it, the reason why it worked is because ```integrateOperations``` merged two changes together (which I should admit is pretty neat), so that they were not dependent on each other and could still be applied, if going backwards.

To close on this - I agree there is no bug in the code and intention of ```old``` and ```new``` is now clear. What I don't agree with is the following statement:

> One more thing to emphasize is that the order of operations doesn't matter.

Order of operations applied to the ```Document``` doesn't (assuming that it will just buffer changes that it cannot apply at the moment). But order of edits returned from ```integrateOperations``` does matter and you have to apply them backwards. I think it would be better, if ```integrateOperations``` would return the edits in the order in which they should be applied to a plain string, rather than backwards.

If you disagree and still believe that order **doesn't** matter, then I have a repro where just changing
```
for (let i = changes.length - 1; i >= 0; i--) {
```
in ```local-document.js:updateText``` to
```
for (let i = 0; i < changes.length; i++) {
```
will produce incorrect ```text``` within local document.

**Comment by as-cii** [comment]
Changes can be applied either in ascending or descending order. When applying them forwards, you should use the new coordinate space:

```js
const oldExtent = traversal(oldEnd, oldStart)
doc.setTextInRange(newStart, traverse(newStart, oldExtent), newText)
```

When applying them backwards, you should use the old coordinate space:

```js
doc.setTextInRange(oldStart, oldEnd, newText)
```

We simply used the latter because it was more concise, but nothing prevents you from applying them forwards and that's the right use case sometimes.

**Comment by nahk-ivanov** [comment]
Yeah, the only thing is that consumer has to perform additional computations to adjust positions himself, which is already done within ```integrateOperations```, so it is not really an option I'd suggest to anyone. My original proposal was aimed at adding something to the resulting edits that can be directly used by consumers to apply changes.

After looking deeply into the tests, I see where I was wrong, as you can just apply the changes in reverse order due to:
1) Changes returned in the order they appear in the document
2) Dependent changes being merged into one

I updated my logic to go backwards and it seems to be working fine on small tests I performed so far, time will tell.

Thanks!
