### ISSUE TITLE
Can teletype-crdt work with other wysiwyg editor ?

### ISSUE THREAD

**Issue by YingshanDeng** [atom/teletype-crdt#6]
Hello! I am interested in this repo. It's great. And  Can teletype-crdt work with other wysiwyg editor, like [CKEditor](https://ckeditor.com/)? I want to apply teletype-crdt to wysiwyg editors, so that they can collaborative editing. Can you give me some advice? Thank u 😊

**Comment by aslakhellesoy** [comment]
Probably not. This CRDT is for text. A wysiwyg editor’s underlying model isn’t text, it’s a tree (with nodes and properties to represent rich text).

**Comment by YingshanDeng** [comment]
Ok. So I can only apply teletype-crdt to a plain text editor? I really want to use teletype-crdt to make a demo about collaborative editing. Can you give me some tips or something about teletyp-crdt applying to atom? Thank u 😊

**Comment by YingshanDeng** [comment]
The Operational Transformation (usually abbreviated OT) is another solution for collaborative editor. The [ot.js](https://github.com/Operational-Transformation/ot.js/) is an implement of OT. Expanding the OT with attributes can make the rich text editor collaboratively. And the [firepad](https://github.com/firebase/firepad) do that.

**Comment by as-cii** [comment]
Hello @YingshanDeng! Like @aslakhellesoy explained, teletype-crdt is a CRDT that exposes APIs that work only with plain text and [markers](https://atom.io/docs/api/v0.208.0/Marker). A WYSIWYG editor has a more complex structure than just text, so you will need to enhance it in such a way that can support your use case.

I am going to close this for now, as we are not interested in providing such support in the library at this time. Thanks for the feedback!
